// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `ErrorCode.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joken.common.rpc;

public enum ErroCode implements java.io.Serializable
{
    
    REQUESTNOPASS(5101),
    
    REQUESTUSERNAMENULL(5102),
    
    REQUESTUSERTOKENNULL(5103);

    public int
    value()
    {
        return __value;
    }

    public static ErroCode
    valueOf(int __v)
    {
        switch(__v)
        {
        case 5101:
            return REQUESTNOPASS;
        case 5102:
            return REQUESTUSERNAMENULL;
        case 5103:
            return REQUESTUSERTOKENNULL;
        }
        return null;
    }

    private
    ErroCode(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 5103);
    }

    public static void
    __write(IceInternal.BasicStream __os, ErroCode __v)
    {
        if(__v == null)
        {
            __os.writeEnum(com.joken.common.rpc.ErroCode.REQUESTNOPASS.value(), 5103);
        }
        else
        {
            __os.writeEnum(__v.value(), 5103);
        }
    }

    public static ErroCode
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(5103);
        return __validate(__v);
    }

    private static ErroCode
    __validate(int __v)
    {
        final ErroCode __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
