// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BaseException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joken.common.rpc;

/**
 * 返回空值异常。当方法返回空值时抛出这个异常，因为ICE不会返回一个空值，只会返回
 * 一个空数据结构，但空数据结构会有默认的初始值。
 *
 **/
public class NullValueException extends BaseException
{
    public NullValueException()
    {
        super();
    }

    public NullValueException(Throwable __cause)
    {
        super(__cause);
    }

    public NullValueException(String reason, String userMessage)
    {
        super(reason, userMessage);
    }

    public NullValueException(String reason, String userMessage, Throwable __cause)
    {
        super(reason, userMessage, __cause);
    }

    public String
    ice_name()
    {
        return "com::joken::common::rpc::NullValueException";
    }

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::com::joken::common::rpc::NullValueException", -1, false);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public static final long serialVersionUID = 2014015387L;
}
