// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `QueryParam.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joken.common.rpc;

public final class SortMapHolder extends Ice.Holder<java.util.Map<java.lang.String, java.lang.String>>
{
    public
    SortMapHolder()
    {
    }

    public
    SortMapHolder(java.util.Map<java.lang.String, java.lang.String> value)
    {
        super(value);
    }
}
