// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var com = __M.require(module, 
    [
        "com/jpgk/common/rpc/BaseException",
        "com/jpgk/common/rpc/BaseService",
        "com/jpgk/common/rpc/Page",
        "com/jpgk/common/rpc/ResponseModel",
        "com/jpgk/filesystem/rpc/FileSystem",
        "com/jpgk/catering/rpc/model/CommonClass"
    ]).com;
    
    var Slice = Ice.Slice;

    com.jpgk = __M.module("com.jpgk");

    com.jpgk.catering = __M.module("com.jpgk.catering");

    com.jpgk.catering.rpc = __M.module("com.jpgk.catering.rpc");

    com.jpgk.catering.rpc.common = __M.module("com.jpgk.catering.rpc.common");

    com.jpgk.catering.rpc.common.CommonService = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            com.jpgk.common.rpc.BaseService
        ], 1,
        [
            "::Ice::Object",
            "::com::jpgk::catering::rpc::common::CommonService",
            "::com::jpgk::common::rpc::BaseService"
        ],
        -1, undefined, undefined, false);

    com.jpgk.catering.rpc.common.CommonServicePrx = Slice.defineProxy(Ice.ObjectPrx, com.jpgk.catering.rpc.common.CommonService.ice_staticId, [
        com.jpgk.common.rpc.BaseServicePrx]);

    Slice.defineOperations(com.jpgk.catering.rpc.common.CommonService, com.jpgk.catering.rpc.common.CommonServicePrx,
    {
        "getDistrictListByPid": [, , , , , ["com.jpgk.catering.rpc.common.DistrictSeqHelper"], [[3]], , , , true],
        "uploadPicture": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[com.jpgk.FileSystem.rpc.UploadModel], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "uploadPictureAndBoundRowId": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[com.jpgk.FileSystem.rpc.UploadModel], [3], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "deletePicture": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3]], , , , ],
        "regenerationPicture": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3]], , , , ],
        "collect": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3], [3], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "cancelCollection": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3], [3], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "cancelCollections": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3], ["com.jpgk.common.rpc.IntSeqenceHelper"], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "share": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[3], [3], [com.jpgk.catering.rpc.common.App.__helper]], , , , ],
        "checkAppVersion": [, , , , , [com.jpgk.common.rpc.ResponseModel], [[7], [com.jpgk.catering.rpc.common.AppType.__helper]], , , , ],
        "getJobs": [, , , , , ["com.jpgk.catering.rpc.common.JobSeqHelper"], , , , , true],
        "contactUs": [, , , , , [7], , , , , ]
    });
    exports.com = com;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
