// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LiveClass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var com = __M.require(module, 
    [
        "com/jpgk/common/rpc/Page",
        "com/jpgk/catering/rpc/common"
    ]).com;
    
    var Slice = Ice.Slice;

    com.jpgk = __M.module("com.jpgk");

    com.jpgk.catering = __M.module("com.jpgk.catering");

    com.jpgk.catering.rpc = __M.module("com.jpgk.catering.rpc");

    com.jpgk.catering.rpc.live = __M.module("com.jpgk.catering.rpc.live");

    /**
     * 直播地址
     **/
    com.jpgk.catering.rpc.live.LivePath = Slice.defineObject(
        function(type, path)
        {
            Ice.Object.call(this);
            this.type = type !== undefined ? type : 0;
            this.path = path !== undefined ? path : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::com::jpgk::catering::rpc::live::LivePath"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.type);
            __os.writeString(this.path);
        },
        function(__is)
        {
            this.type = __is.readInt();
            this.path = __is.readString();
        },
        false);

    com.jpgk.catering.rpc.live.LivePathPrx = Slice.defineProxy(Ice.ObjectPrx, com.jpgk.catering.rpc.live.LivePath.ice_staticId, undefined);

    Slice.defineOperations(com.jpgk.catering.rpc.live.LivePath, com.jpgk.catering.rpc.live.LivePathPrx);
    Slice.defineSequence(com.jpgk.catering.rpc.live, "LivePathSeqHelper", "Ice.ObjectHelper", false, "com.jpgk.catering.rpc.live.LivePath");

    /**
     * 直播间
     **/
    com.jpgk.catering.rpc.live.LiveRoom = Slice.defineObject(
        function(id, title, speaker, livePaths, statusShow, coverUrl, description, onlineUserNum)
        {
            Ice.Object.call(this);
            this.id = id !== undefined ? id : 0;
            this.title = title !== undefined ? title : "";
            this.speaker = speaker !== undefined ? speaker : "";
            this.livePaths = livePaths !== undefined ? livePaths : null;
            this.statusShow = statusShow !== undefined ? statusShow : "";
            this.coverUrl = coverUrl !== undefined ? coverUrl : "";
            this.description = description !== undefined ? description : "";
            this.onlineUserNum = onlineUserNum !== undefined ? onlineUserNum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::com::jpgk::catering::rpc::live::LiveRoom"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.id);
            __os.writeString(this.title);
            __os.writeString(this.speaker);
            com.jpgk.catering.rpc.live.LivePathSeqHelper.write(__os, this.livePaths);
            __os.writeString(this.statusShow);
            __os.writeString(this.coverUrl);
            __os.writeString(this.description);
            __os.writeInt(this.onlineUserNum);
        },
        function(__is)
        {
            this.id = __is.readInt();
            this.title = __is.readString();
            this.speaker = __is.readString();
            this.livePaths = com.jpgk.catering.rpc.live.LivePathSeqHelper.read(__is);
            this.statusShow = __is.readString();
            this.coverUrl = __is.readString();
            this.description = __is.readString();
            this.onlineUserNum = __is.readInt();
        },
        false);

    com.jpgk.catering.rpc.live.LiveRoomPrx = Slice.defineProxy(Ice.ObjectPrx, com.jpgk.catering.rpc.live.LiveRoom.ice_staticId, undefined);

    Slice.defineOperations(com.jpgk.catering.rpc.live.LiveRoom, com.jpgk.catering.rpc.live.LiveRoomPrx);
    Slice.defineSequence(com.jpgk.catering.rpc.live, "LiveRoomSeqHelper", "Ice.ObjectHelper", false, "com.jpgk.catering.rpc.live.LiveRoom");
    exports.com = com;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
