// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Page.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var com = __M.module("com");

    com.jpgk = __M.module("com.jpgk");

    com.jpgk.common = __M.module("com.jpgk.common");

    com.jpgk.common.rpc = __M.module("com.jpgk.common.rpc");
    Slice.defineDictionary(com.jpgk.common.rpc, "ParamsMap", "ParamsMapHelper", "Ice.StringHelper", "Ice.StringHelper", false, undefined, undefined);

    /**
     * 分页实体类
     **/
    com.jpgk.common.rpc.Page = Slice.defineStruct(
        function(pageNum, pageSize, pageTotal, totalNum, params)
        {
            this.pageNum = pageNum !== undefined ? pageNum : 0;
            this.pageSize = pageSize !== undefined ? pageSize : 0;
            this.pageTotal = pageTotal !== undefined ? pageTotal : 0;
            this.totalNum = totalNum !== undefined ? totalNum : 0;
            this.params = params !== undefined ? params : null;
        },
        false,
        function(__os)
        {
            __os.writeInt(this.pageNum);
            __os.writeInt(this.pageSize);
            __os.writeInt(this.pageTotal);
            __os.writeInt(this.totalNum);
            com.jpgk.common.rpc.ParamsMapHelper.write(__os, this.params);
        },
        function(__is)
        {
            this.pageNum = __is.readInt();
            this.pageSize = __is.readInt();
            this.pageTotal = __is.readInt();
            this.totalNum = __is.readInt();
            this.params = com.jpgk.common.rpc.ParamsMapHelper.read(__is);
        },
        17, 
        false);
    exports.com = com;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
