// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `FileSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joken.FileSystem.rpc;

/**
 * 上传文件返回模型
 *
 **/
public class FileModel implements java.lang.Cloneable, java.io.Serializable
{
    /**
     * 文件保存记录标识
     **/
    public int fileId;

    /**
     * 文件保存记录标识
     **/
    public int
    getFileId()
    {
        return fileId;
    }

    /**
     * 文件保存记录标识
     **/
    public void
    setFileId(int _fileId)
    {
        fileId = _fileId;
    }

    /**
     * 本地路径
     **/
    public String localPath;

    /**
     * 本地路径
     **/
    public String
    getLocalPath()
    {
        return localPath;
    }

    /**
     * 本地路径
     **/
    public void
    setLocalPath(String _localPath)
    {
        localPath = _localPath;
    }

    /**
     * http路径
     **/
    public String urlPath;

    /**
     * http路径
     **/
    public String
    getUrlPath()
    {
        return urlPath;
    }

    /**
     * http路径
     **/
    public void
    setUrlPath(String _urlPath)
    {
        urlPath = _urlPath;
    }

    public FileModel()
    {
        localPath = "";
        urlPath = "";
    }

    public FileModel(int fileId, String localPath, String urlPath)
    {
        this.fileId = fileId;
        this.localPath = localPath;
        this.urlPath = urlPath;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FileModel _r = null;
        if(rhs instanceof FileModel)
        {
            _r = (FileModel)rhs;
        }

        if(_r != null)
        {
            if(fileId != _r.fileId)
            {
                return false;
            }
            if(localPath != _r.localPath)
            {
                if(localPath == null || _r.localPath == null || !localPath.equals(_r.localPath))
                {
                    return false;
                }
            }
            if(urlPath != _r.urlPath)
            {
                if(urlPath == null || _r.urlPath == null || !urlPath.equals(_r.urlPath))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::com::joken::FileSystem::rpc::FileModel");
        __h = IceInternal.HashUtil.hashAdd(__h, fileId);
        __h = IceInternal.HashUtil.hashAdd(__h, localPath);
        __h = IceInternal.HashUtil.hashAdd(__h, urlPath);
        return __h;
    }

    public FileModel
    clone()
    {
        FileModel c = null;
        try
        {
            c = (FileModel)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(fileId);
        __os.writeString(localPath);
        __os.writeString(urlPath);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        fileId = __is.readInt();
        localPath = __is.readString();
        urlPath = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, FileModel __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FileModel
    __read(IceInternal.BasicStream __is, FileModel __v)
    {
        if(__v == null)
        {
             __v = new FileModel();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FileModel __nullMarshalValue = new FileModel();

    public static final long serialVersionUID = 1731292029L;
}
