// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `FileSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joken.FileSystem.rpc;

/**
 * 板块异常类型。
 *
 **/
public class UploadException extends com.joken.common.rpc.BaseException
{
    public UploadException()
    {
        super();
    }

    public UploadException(Throwable __cause)
    {
        super(__cause);
    }

    public UploadException(String reason, String userMessage)
    {
        super(reason, userMessage);
    }

    public UploadException(String reason, String userMessage, Throwable __cause)
    {
        super(reason, userMessage, __cause);
    }

    public String
    ice_name()
    {
        return "com::joken::FileSystem::rpc::UploadException";
    }

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::com::joken::FileSystem::rpc::UploadException", -1, false);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public static final long serialVersionUID = -1263853978L;
}
